[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_solana = "5MwohuA1kjtkXfugMqchkyhnUjWZQf9GGWgnHTyW1977"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hackerboy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
